export type Game = {
  id: string;
  name: string;
  shortName: string;
  emoji: string;
  gradient: string;
  bg: string;
  border: string;
  text: string;
  category: string;
  description: string;
  maxPlayers: number;
};

export const GAMES: Game[] = [
  {
    id: "cs2",
    name: "Counter-Strike 2",
    shortName: "CS2",
    emoji: "🔫",
    gradient: "from-amber-500 to-orange-600",
    bg: "bg-amber-500/10",
    border: "border-amber-500/30",
    text: "text-amber-400",
    category: "FPS",
    description: "Efsanevi taktiksel FPS",
    maxPlayers: 10,
  },
  {
    id: "valorant",
    name: "Valorant",
    shortName: "Valorant",
    emoji: "🎯",
    gradient: "from-red-500 to-rose-600",
    bg: "bg-red-500/10",
    border: "border-red-500/30",
    text: "text-red-400",
    category: "FPS",
    description: "Taktik tabanlı ajan FPS",
    maxPlayers: 10,
  },
  {
    id: "lol",
    name: "League of Legends",
    shortName: "LoL",
    emoji: "⚔️",
    gradient: "from-blue-500 to-cyan-400",
    bg: "bg-blue-500/10",
    border: "border-blue-500/30",
    text: "text-blue-400",
    category: "MOBA",
    description: "Dünyanın en popüler MOBA'sı",
    maxPlayers: 10,
  },
  {
    id: "dota2",
    name: "Dota 2",
    shortName: "Dota 2",
    emoji: "🛡️",
    gradient: "from-red-700 to-red-900",
    bg: "bg-red-700/10",
    border: "border-red-700/30",
    text: "text-red-500",
    category: "MOBA",
    description: "Derinlikli strateji MOBA",
    maxPlayers: 10,
  },
  {
    id: "fifa",
    name: "EA Sports FC",
    shortName: "FC 25",
    emoji: "⚽",
    gradient: "from-green-500 to-emerald-600",
    bg: "bg-green-500/10",
    border: "border-green-500/30",
    text: "text-green-400",
    category: "Spor",
    description: "Sanal saha, gerçek heyecan",
    maxPlayers: 22,
  },
  {
    id: "wow",
    name: "World of Warcraft",
    shortName: "WoW",
    emoji: "🐉",
    gradient: "from-yellow-600 to-amber-800",
    bg: "bg-yellow-600/10",
    border: "border-yellow-600/30",
    text: "text-yellow-500",
    category: "MMORPG",
    description: "Efsanevi MMORPG deneyimi",
    maxPlayers: 40,
  },
  {
    id: "metin2",
    name: "Metin2",
    shortName: "Metin2",
    emoji: "🗡️",
    gradient: "from-purple-600 to-violet-800",
    bg: "bg-purple-600/10",
    border: "border-purple-600/30",
    text: "text-purple-400",
    category: "MMORPG",
    description: "Nostalji dolu aksiyon RPG",
    maxPlayers: 8,
  },
  {
    id: "minecraft",
    name: "Minecraft",
    shortName: "MC",
    emoji: "⛏️",
    gradient: "from-green-600 to-lime-500",
    bg: "bg-green-600/10",
    border: "border-green-600/30",
    text: "text-green-400",
    category: "Sandbox",
    description: "Sınırsız yaratıcılık dünyası",
    maxPlayers: 20,
  },
  {
    id: "fortnite",
    name: "Fortnite",
    shortName: "Fortnite",
    emoji: "🏗️",
    gradient: "from-indigo-500 to-purple-600",
    bg: "bg-indigo-500/10",
    border: "border-indigo-500/30",
    text: "text-indigo-400",
    category: "Battle Royale",
    description: "İnşa et, savaş, kazan",
    maxPlayers: 4,
  },
  {
    id: "pubg",
    name: "PUBG",
    shortName: "PUBG",
    emoji: "🪖",
    gradient: "from-yellow-700 to-orange-800",
    bg: "bg-yellow-700/10",
    border: "border-yellow-700/30",
    text: "text-yellow-600",
    category: "Battle Royale",
    description: "Battle Royale'in öncüsü",
    maxPlayers: 4,
  },
  {
    id: "apex",
    name: "Apex Legends",
    shortName: "Apex",
    emoji: "🦅",
    gradient: "from-red-600 to-orange-500",
    bg: "bg-red-600/10",
    border: "border-red-600/30",
    text: "text-red-400",
    category: "Battle Royale",
    description: "Hızlı tempolu BR aksiyonu",
    maxPlayers: 3,
  },
  {
    id: "gta5",
    name: "GTA V Online",
    shortName: "GTA V",
    emoji: "🚗",
    gradient: "from-lime-500 to-green-700",
    bg: "bg-lime-500/10",
    border: "border-lime-500/30",
    text: "text-lime-400",
    category: "Açık Dünya",
    description: "Suç dünyasında macera",
    maxPlayers: 30,
  },
  {
    id: "r6",
    name: "Rainbow Six Siege",
    shortName: "R6",
    emoji: "🔰",
    gradient: "from-slate-400 to-slate-600",
    bg: "bg-slate-400/10",
    border: "border-slate-400/30",
    text: "text-slate-300",
    category: "FPS",
    description: "Taktiksel takım FPS",
    maxPlayers: 10,
  },
  {
    id: "overwatch",
    name: "Overwatch 2",
    shortName: "OW2",
    emoji: "🦸",
    gradient: "from-orange-400 to-amber-500",
    bg: "bg-orange-400/10",
    border: "border-orange-400/30",
    text: "text-orange-400",
    category: "FPS",
    description: "Kahraman tabanlı takım FPS",
    maxPlayers: 10,
  },
  {
    id: "rocketleague",
    name: "Rocket League",
    shortName: "RL",
    emoji: "🚀",
    gradient: "from-sky-500 to-blue-600",
    bg: "bg-sky-500/10",
    border: "border-sky-500/30",
    text: "text-sky-400",
    category: "Spor",
    description: "Arabalı futbol çılgınlığı",
    maxPlayers: 6,
  },
  {
    id: "elden-ring",
    name: "Elden Ring",
    shortName: "ER",
    emoji: "💍",
    gradient: "from-yellow-500 to-yellow-700",
    bg: "bg-yellow-500/10",
    border: "border-yellow-500/30",
    text: "text-yellow-400",
    category: "RPG",
    description: "Epik açık dünya RPG zorluğu",
    maxPlayers: 4,
  },
  {
    id: "diablo4",
    name: "Diablo IV",
    shortName: "D4",
    emoji: "😈",
    gradient: "from-red-800 to-red-950",
    bg: "bg-red-800/10",
    border: "border-red-800/30",
    text: "text-red-500",
    category: "ARPG",
    description: "Karanlık aksiyon RPG",
    maxPlayers: 4,
  },
  {
    id: "deadlock",
    name: "Deadlock",
    shortName: "DL",
    emoji: "💀",
    gradient: "from-teal-500 to-emerald-700",
    bg: "bg-teal-500/10",
    border: "border-teal-500/30",
    text: "text-teal-400",
    category: "MOBA Shooter",
    description: "Valve'ın yeni MOBA shooter'ı",
    maxPlayers: 12,
  },
];

export function getGameById(id: string): Game | undefined {
  return GAMES.find((g) => g.id === id);
}

export function getGameByName(name: string): Game | undefined {
  return GAMES.find(
    (g) =>
      g.name.toLowerCase() === name.toLowerCase() ||
      g.shortName.toLowerCase() === name.toLowerCase()
  );
}

export const GAME_CATEGORIES = [
  "FPS",
  "MOBA",
  "MMORPG",
  "Battle Royale",
  "Spor",
  "RPG",
  "ARPG",
  "Sandbox",
  "Açık Dünya",
  "MOBA Shooter",
];
